### ISSUE TITLE
Set Authentication Token

### ISSUE THREAD

**Issue by wardjm** [dxFeed/dxfeed-c-api#99]
Does the C implementation have a way to set an authentication token? The JavaScript implementation has code such as:

import Feed, { EventType } from '@dxfeed/api'
const feed = new Feed()
feed.setAuthToken('myFakeDxFeedAuthToken')
feed.connect('https://fakestreamerurl.dxfeed.com')

But is unclear whether this exists in this project. I browsed the examples and header files and it doesn't appear to exist. Sorry if I'm overlooking something obvious, but I'm very new to this project.

**Comment by jrwats** [comment]
Full disclosure: Not a dxfeed engineer, but I'm a downstream user of the C API, via [our rust wrapper](https://crates.io/crates/dxfeed)

I believe `create_connection_auth_bearer` are the droids you're looking for
```
create_connection_auth_bearer(
                 host,            // const char* address,
                 token,           // const char* token,
                 termination_listener, // dxf_conn_termination_notifier_t notifier,
                 sub_listener,         // dxf_conn_status_notifier_t conn_status_notifier,
                 nullptr,                       // dxf_socket_thread_creation_notifier_t stcn,
                 nullptr,                       // dxf_socket_thread_destruction_notifier_t stdn,
                 nullptr,       // void* user_data,
                 &conn,                  // OUT dxf_connection_t* connection);
)
```

**Comment by wardjm** [comment]
Thanks so much! I guess my searching was too restrictive. I should have looked for just "auth". This looks good to me!

**Comment by Strotsev** [comment]
@wardjm from the dxfeed team's side, I can confirm that @jrwats gave you the correct method :) Thanks John!
Here is [the link](https://docs.dxfeed.com/c-api/group__c-api-connection-functions.html#gab8e9e8e63aa99b525ce32ed003c0fb2b) to the documentation.
And here is [the link](https://github.com/dxFeed/dxfeed-c-api/blob/master/samples/CommandLineSample/CommandLineSample.c#L762) to an example where this method is used.
If you still have questions or new ones appear, you can also ask them on [our portal](https://jira.in.devexperts.com/servicedesk/customer/portal/1).
